name: maouidi
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # Core packages - UPDATED
  app_links: ^6.4.1
  auto_size_text: ^3.0.0
  cached_network_image: ^3.3.1
  collection: ^1.18.0
  dropdown_button2: ^2.3.9
  flutter_animate: ^4.5.0
  flutter_cache_manager: ^3.3.2
  flutter_keyboard_visibility: ^6.0.0
  font_awesome_flutter: ^10.7.0
  from_css_color: ^2.0.0
  functions_client: ^2.4.4
  go_router: ^14.1.0
  google_fonts: ^6.2.1
  google_nav_bar: ^5.0.6
  gotrue: ^2.15.0
  hive: ^2.2.3
  intl: ^0.20.2
  json_path: ^0.7.1
  page_transition: ^2.1.0
  path_provider: ^2.1.3
  postgrest: ^2.5.0
  provider: ^6.1.2
  realtime_client: ^2.5.3
  shared_preferences: ^2.2.3
  sign_in_with_apple: ^6.1.1
  sqflite: ^2.3.3+1
  sqflite_common: ^2.5.4
  storage_client: ^2.4.1
  supabase: ^2.9.2
  supabase_flutter: ^2.10.2
  table_calendar: ^3.1.2
  timeago: ^3.6.1
  url_launcher: ^6.3.0
  webview_flutter: ^4.8.0
  image_picker: ^1.1.2

  # Additional UI packages
  cupertino_icons: ^1.0.8
  flutter_datetime_picker_plus: ^2.1.0
  flutter_rating_bar: ^4.0.1
  fl_chart: ^0.68.0
  onesignal_flutter: ^5.2.2
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_lints: ^4.0.0
  lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/jsons/
    - .env